### ISSUE TITLE
Delete edges that are not used by any other surface when deleting a surface topo object.

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#10]
Whats best way to remove edges that not visible in a surface layer even is the edge is used by another linestring layer.

Ses a more detailed description in the attached file.
[Delete_unused_surface_edges.pdf](https://github.com/NibioOpenSource/pgtopo_update_sql/files/20220/Delete_unused_surface_edges.pdf)

**Comment by strk** [comment]
It looks to me that your main question here is how to figure out
which edges fall inside the space that you just removed, is that
correct ?

I don't know exactly how you delete a surface object, but I guess
you first add a new TopoGeometry representing the surface to be
removed and then remove the faces defining the "to-be-removed"
TopoGeometry from the definition of any other TopoGeometry ?

If that's the case then you have a set of faces and want to remove
any edge whose left and right faces are both in the set.

In order to remove those edges you'll first need to remove them
from the definition of any existing linear TopoGeometry, which
involves a delete from the "relation" table.

Does the above help ?

**Comment by larsop** [comment]
Yes that's correct I need to find out what edges that fall inside the geometry just deleted.

I would like to do this with out using  a geometry function like ST_Intersects but instead use the topology relation tables. But I was not able figure out how to write this sql.

To delete the surface object I use clearTopoGeom and then delete the row afterwords.

Thanks Lars

**Comment by larsop** [comment]
TO delete I use 
PERFORM clearTopoGeom(omrade) FROM topo_rein.arstidsbeite_var_flate r
WHERE id = id_in;
DELETE FROM topo_rein.arstidsbeite_var_flate r
WHERE id = id_in;

Se more info in the attached file
[Delete_unused_surface_edges_2.pdf](https://github.com/NibioOpenSource/pgtopo_update_sql/files/20419/Delete_unused_surface_edges_2.pdf)

**Comment by strk** [comment]
I've pushed a function to obtain an array of edge identifiers from a TopoGeometry object.
The edges identified by the elements of the returned array are known to be inside the input TopoGeometry surface. See function_01_get_edges_within_topo_surface.sql file.

I guess the next step would be finding all the linear TopoGeometry objects defined by any of those edges, which may be done with something like this:

```
SELECT r.topogeo_id, r.layer_id from topo_rein_sysdata.relation r, topology.layer l 
WHERE r.layer_id = l.layer_id and l.level = 0 -- non hierarchical
      AND element_type = 2 -- edge component
      AND element_id in ( get_edges_within_topo_surface(xxx) );
```

Note that a linear TopoGeometry may be only partially defined by an edge within the removed surface, so you might not want to use clearTopoGeom against it but rather only update it to drop
from its definition the edges returned by the above query.

I think it would be a good idea to have more TopoGeometry editing functions in PostGIS core to do things like that, with signatures like:

```
 TopoGeometry topology.AddTopoGeomElement(TopoElement);
 TopoGeometry topology.DelTopoGeomElement(TopoElement);
```

**Comment by larsop** [comment]
I have problems to use topo_rein.get_edges_within_toposurface.

I have now added this code to se what happens  when I use it

```
DROP TABLE IF EXISTS topo_rein.edges_within;
CREATE TABLE topo_rein.edges_within AS 
(
select topo_rein.get_edges_within_toposurface(omrade), omrade FROM topo_rein.arstidsbeite_var_flate WHERE id = id_in
);
PERFORM clearTopoGeom(omrade) FROM topo_rein.arstidsbeite_var_flate r
WHERE id = id_in;
DELETE FROM topo_rein.arstidsbeite_var_flate r
WHERE id = id_in;
```

In the the table I created I find the following result

[local] lop@sl=# select \* from topo_rein.edges_within;
 get_edges_within_toposurface |   omrade  
------------------------------+-------------
 [NULL]                       | (554,2,7,3)
(1 row)

Do you see what the problem is ?

**Comment by strk** [comment]
Can you send a dump of your test database for me to try it locally ?
Or point me to scripts in the repo to build the test dataset up ?

**Comment by strk** [comment]
After receiving the dump and looking at it, I confirm that the function output is correct because there are no interior edges in the TopoGeometry surfaces stored in the topo_rein.arstidsbeite_var_flate table.

**Comment by larsop** [comment]
Ok, I try explain the problem in another way. 

In the database dump I sent you there are 2 records in the topo_rein_sysdata.edge that I need to find and delete. They have edge_id = 2 and edge_id = 5.

How do I find them ?

Whats the best way to delete them ?

**Comment by larsop** [comment]
If you check the content of topo_rein.arstidsbeite_var_flate_v, this two egdes should by outside any of the surfaces.

**Comment by strk** [comment]
ok so you want to reverse the check not to find edges within a TopoGeometry surface but those NOT being within any TopoGeometry. It still starts from getting the list of faces not used in the definition of any TopoGeometry and then finding the edges that have those faces on both sides.
Is this correct ?

Yes that sound correct.
When I call delete of a surface topo object I will also remove any edges that are not used by any surface topo object any more.

**Comment by strk** [comment]
Note that such edges might still be in use by lineal TopoGeometry objects, do you still want them output ?

**Comment by larsop** [comment]
Yes they will alway used by lineal TopoGeometry objects so I have the change this lineal topo objects to not include these edges also.

**Comment by strk** [comment]
So to rephrase, you're looking for edges that are not covered by any TopoGeometry.
I've pushed a get_unused_faces function to extract the list of faces not taking part of the definition of any TopoGeometry and a get_edges_within_faces function to obtain the list of edges that fall within those faces.

So the edges you are looking for should be obtainable with this select:

```
select                                                                          
 topo_rein.get_edges_within_faces(array_agg(x)) from                            
 topo_rein.get_unused_faces() x;  
```

The above query give me `{2,5}` for the test dataset, which is correct as far as I can tell.

**Comment by strk** [comment]
further rephrase: you're looking for edges that are not covered by any _areal_ TopoGeometry.

**Comment by larsop** [comment]
Yes thats's correct.

**Comment by larsop** [comment]
The function topo_rein.get_unused_faces and topo_rein.get_edges_within_faces works as expected.

Then I can go to the next phase.

Thanks

**Comment by larsop** [comment]
The code is now tested, had to add parameter to select what layers to check on.

Thanks
