### ISSUE TITLE
Takes long time to produce topoJson

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#12]
Hi

In the example below we see that is takes less 100 ms to find the rows but to return the topoJson for those rows takes more 16000 ms. 

Do you have any clues on how to fix this ?

-- This is how the sql is called from the code execpt that we do not get length but the topJson
select length(topo_rein.query_to_topojson('select distinct a.\* from topo_rein.arstidsbeite_var_topojson_flate_v a ,topo_rein_sysdata.face fa, topo_rein_sysdata.relation re, topology.layer tl WHERE fa.mbr && ST_GeomFromEWKT(''POLYGON ((9.609839108612533 67.70153849237619, 8.564405958195684 71.4611114249892, 32.60829816266885 70.72892872531436, 29.86836714875339 67.09878623581699, 9.609839108612533 67.70153849237619))'') AND topo_rein.get_relation_id(a.omrade) = re.topogeo_id AND re.layer_id = tl.layer_id AND tl.schema_name = ''topo_rein'' AND tl.table_name = ''arstidsbeite_var_flate'' and fa.face_id=re.element_id',32633,0));
##  length  

 5949302
(1 row)
Time: 16156.707 ms

-- Here is sql that is used find the rows to be used
select count(distinct a.*) from topo_rein.arstidsbeite_var_topojson_flate_v a ,topo_rein_sysdata.face fa, topo_rein_sysdata.relation re, topology.layer tl
WHERE fa.mbr && ST_GeomFromEWKT('POLYGON ((9.609839108612533 67.70153849237619, 8.564405958195684 71.4611114249892, 32.60829816266885 70.72892872531436, 29.86836714875339 67.09878623581699, 9.609839108612533 67.70153849237619))') AND topo_rein.get_relation_id(a.omrade) = re.topogeo_id AND re.layer_id = tl.layer_id AND tl.schema_name = 'topo_rein' AND tl.table_name = 'arstidsbeite_var_flate' and fa.face_id=re.element_id
##  count 

   518
(1 row)
Time: 83.224 ms

Lars

**Comment by larsop** [comment]
I have now moved this data to separate topology schema topo_rein_sysdata_rvr and then it goes about 8 times faster.

select length(topo_rein.query_to_topojson('select distinct a.\* from topo_rein.arstidsbeite_var_topojson_flate_v a ,topo_rein_sysdata_rvr.face fa, topo_rein_sysdata_rvr.relation re, topology.layer tl WHERE fa.mbr && ST_GeomFromEWKT(''POLYGON ((9.609839108612533 67.70153849237619, 8.564405958195684 71.4611114249892, 32.60829816266885 70.72892872531436, 29.86836714875339 67.09878623581699, 9.609839108612533 67.70153849237619))'') AND topo_rein.get_relation_id(a.omrade) = re.topogeo_id AND re.layer_id = tl.layer_id AND tl.schema_name = ''topo_rein'' AND tl.table_name = ''arstidsbeite_var_flate'' and fa.face_id=re.element_id',32633,0));

## length  

 5509029
(1 row)

Time: 1899.083 ms

**Comment by strk** [comment]
You should check the inner query (the one passed as first parameter to query_to_topojson) with EXPLAIN. Is an index used on both machines ? Does time change after you run ANALYZE  ?
How many edges and faces are in the topology ?

I could answer to these questions and more if you could give me access to the subject host.

**Comment by larsop** [comment]
Here is as dump of this layer

[topjson_db.dump.gz](https://github.com/NibioOpenSource/pgtopo_update_sql/files/85425/topjson_db.dump.gz)

**Comment by strk** [comment]
The topo_rein_sysdata.face table is empty in the dump (except for the universe face), and the selection query consequently returns 0 rows here. I see you're using `topo_rein_sysdata_rvr` in your second query (reported to be 8 times faster) but `topo_rein_sysdata` in the first query. What is the difference between the two ?

**Comment by strk** [comment]
The selection query against the `_rvr` topology returns 519 rows in 14.485 ms here, while the corresponding toTopoJSON (length) takes 1934.982 seconds.

**Comment by larsop** [comment]
All data for this table are now moved to topo_rein_sysdata_rvr so we have different topology names for each table, since there is no need for sharing edges between layers.

Do you think it is possible to get down time to produce the topoJSON ?

This topoJson is used by the client so this feels quite slow for the end user.

**Comment by strk** [comment]
about 1.67 seconds is the time it takes to execute topology.asTopoJSON for each of the 670 TopoGeometry objects, not including any user attribute:

{{{
select sum(length(astopojson(omrade, 'topo_rein_topojson_edgemap'))) from topo_rein.arstidsbeite_var_flate;
}}}

Adding an index to the "edge_id" field helps some, but not much
(reduces the time from 1.67 seconds to 1.42). 

I'll dig further to see where the time is spent.

**Comment by strk** [comment]
I've a local patch for "AsTopoJSON" that brings down the core time from ~1.7 to ~1.1. Adding an index to the edge map (in pgtopo_update_sql) further reduces the time of the core call to ~.8 seconds.
Further speedups, I'm afraid, would take reimplementing the AsTopoJSON function in C.

**Comment by larsop** [comment]
Thanks, thats great, I will test it soon, right now my code i broken.

Is difficult to merge many topoJson result together to one topoJson.

To get up the speed more I could maybe split the area up in to smaller parts and run in parallel
from the java code and then merge it at the end ?

**Comment by strk** [comment]
To speed up more you could build the TopoJSON directly on the Java side, fetching all the edges falling in the area of interest and building all rings.

**Comment by strk** [comment]
The index change was added with commit f7e0e2bdb0c5000edd66b4c7afa20f1a71f0edff, the PostGIS side is in trunk: https://trac.osgeo.org/postgis/changeset/14591

With these two changes, it takes 527 seconds on my machine to run the core part:

```
LOG:  duration: 527.408 ms  statement: select sum(length(astopojson(omrade,null))) from topo_rein.arstidsbeite_var_flate;
```

Up to 803 ms with indexed edgemap lookups
(required to avoid holes in the arcs array in final output):

```
LOG:  duration: 803.114 ms  statement: select sum(length(astopojson(omrade,'topo_rein_topojson_edgemap'))) from topo_rein.arstidsbeite_var_flate;
```

And 1325 ms for the full query (+522ms), which involves transforming and converting to JSON all of the 2627 arcs.

```
LOG:  duration: 1325.091 ms  statement: select length(topo_rein.query_to_topojson('select distinct a.* from topo_rein.arstidsbeite_var_topojson_flate_v a ,topo_rein_sysdata_rvr.face fa, topo_rein_sysdata_rvr.relation re, topology.layer tl WHERE fa.mbr && ST_GeomFromEWKT(''POLYGON ((9.609839108612533 67.70153849237619, 8.564405958195684 71.4611114249892, 32.60829816266885 70.72892872531436, 29.86836714875339 67.09878623581699, 9.609839108612533 67.70153849237619))'') AND topo_rein.get_relation_id(a.omrade) = re.topogeo_id AND re.layer_id = tl.layer_id AND tl.schema_name = ''topo_rein'' AND tl.table_name = ''arstidsbeite_var_flate'' and fa.face_id=re.element_id',32633,0));
```

Another way to speed things up could be reducing edges by removing nodes that are only attached to two edges, although having very long edges might slow down adding more inputs.

**Comment by larsop** [comment]
Confirmed I get the same numbers on my pc. Thanks.
