### ISSUE TITLE
update_features

### ISSUE THREAD

**Issue by strk** [NibioOpenSource/pgtopo_update_sql#16]
Write a `topo_update.update_features`  function for updating feature changes 

  - Function incoming argument:
      - JSON containing spatial features (areal, lineal) with attributes
        (and uinique identifiers)
      - Name of a topology
      - Reference to a TopoGeometry areal layer (table name, column name)
      - Reference to a TopoGeometry lineal layer (table name, column name)
      - A tolerance (for determining spatial modification)

  - Function should:
      - Find out which features have been added (based on primary key)
        and add them into the referenced TopoGeometry layer
      - Find out which features have been deleted (based on primary key)
        and delete them from the referenced TopoGeometry layer
      - Find out which features have updated _attributes_
        (based on primary key) and update the attributes accordingly
      - Find out which features have changed _spatially_
        (based on primary key) and update the TopoGeometry column
        accordingly

**Comment by larsop** [comment]
{"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"EPSG:25833"}},"features":[{"type":"Feature","geometry":{"type":"LineString","coordinates":[[365995.22000000005,7229536.49],[365995.85000000006,7229538.0],[365996.52,7229538.89],[365997.93,7229539.61],[365999.49,7229540.08],[366000.25,7229540.22],[366003.4,7229540.3],[366004.53,7229539.73],[366005.52,7229538.86],[366006.25,7229535.8],[366005.81,7229533.5],[366004.78,7229531.72],[366003.36,7229531.0],[366001.45,7229530.39],[365999.3,7229530.43],[365998.25,7229530.85],[365996.78,7229531.78],[365995.18,7229534.46],[365995.22000000005,7229536.49]]},"properties":{"featuretype":"ArealressursGrense","datafangstdato":"1965-07-22","verifiseringsdato":"1965-07-22","avgrensingType":"3000","opphav":"FKB-Vann","kvalitet":{"målemetode":"53","nøyaktighet":200,"synbarhet":"0"},"registreringsversjon":{"produkt":"FKB-AR5","versjon":"4.5 20140301"},"identifikasjon":{"navnerom":"AR5_test23","lokalId":"092688bb-c6ef-43c9-b6f7-41b2f065537c","versjonId":"2019-11-11 11:57:47.371000"},"oppdateringsdato":"2019-11-12T14:02:26"}},{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[365995.22000000005,7229536.49],[365995.18,7229534.46],[365996.78,7229531.78],[365998.25,7229530.85],[365999.3,7229530.43],[366001.45,7229530.39],[366003.36,7229531.0],[366004.78,7229531.72],[366005.81,7229533.5],[366006.25,7229535.8],[366005.52,7229538.86],[366004.53,7229539.73],[366003.4,7229540.3],[366000.25,7229540.22],[365999.49,7229540.08],[365997.93,7229539.61],[365996.52,7229538.89],[365995.85000000006,7229538.0],[365995.22000000005,7229536.49]]]},"properties":{"featuretype":"ArealressursFlate","arealtype":"81","treslag":"98","skogbonitet":"98","grunnforhold":"98","kartstandard":"AR5","datafangstdato":"1965-07-22","verifiseringsdato":"1965-07-22","opphav":"FKB-Vann","kvalitet":{"målemetode":"82","nøyaktighet":1,"synbarhet":"0"},"registreringsversjon":{"produkt":"FKB-AR5","versjon":"4.5 20140301"},"identifikasjon":{"navnerom":"AR5_test23","lokalId":"0008e6eb-1332-4145-9943-591020916480","versjonId":"2019-11-11 11:57:47.371000"},"oppdateringsdato":"2019-11-12T14:02:26"},"geometry_properties":{"position":[366000.4,7229534.88],"exterior":["-092688bb-c6ef-43c9-b6f7-41b2f065537c"]}}]}

**Comment by strk** [comment]
For the record: the above is a sample JSON argument to pass to the function

**Comment by larsop** [comment]
> For the record: the above is a sample JSON argument to pass to the function

Yes

**Comment by larsop** [comment]
> > For the record: the above is a sample JSON argument to pass to the function
> 
> Yes
But will probably use the same epsg as in the database and not utm as here.

**Comment by larsop** [comment]
With this change in the python code 

--- a/ngis_openapi/api/features_api.py
+++ b/ngis_openapi/api/features_api.py
@@ -146,7 +146,7 @@ class FeaturesApi(object):
         body_params = None
         # HTTP header `Accept`
         header_params['Accept'] = self.api_client.select_header_accept(
-            ['application/vnd.kartverket.sosi+gml; version=1.0', 'application/vnd.kartverket.sosi+json; version=1.0'])  # noqa: E501
+            ['application/vnd.kartverket.sosi+json; version=1.0'])  # noqa: E501





```
{'crs': {'properties': {'name': 'EPSG:4326'}, 'type': 'name'},
 'features': [{'geometry': {'coordinates': [[65.04253649064205,
                                             12.14516200680029],
                                            [65.04250247301262,
                                             12.145167560483914],
                                            [65.04244186329662,
                                             12.145101987019594],
                                            [65.04239744926669,
                                             12.14503808156186],
                                            [65.04236097241302,
                                             12.144952495402505],
                                            [65.04232213184932,
                                             12.144837190767188],
                                            [65.04229763911421,
                                             12.144749047003048],
                                            [65.0422760952105,
                                             12.14462253864726],
                                            [65.04226790536023,
                                             12.144480571732384],
                                            [65.04227610740607,
                                             12.144374048993429],
                                            [65.04228240402718,
                                             12.144257101915919]],
                            'type': 'LineString'},
               'properties': {'avgrensingType': '4206',
                              'datafangstdato': '1987-07-01',
                              'featuretype': 'ArealressursGrense',
                              'identifikasjon': {'lokalId': '0005d816-cdd6-45ae-8ee2-bcb4785c2a75',
                                                 'navnerom': 'AR5_test23',
                                                 'versjonId': '2019-11-11 '
                                                              '11:57:47.371000'},
                              'kvalitet': {'målemetode': '32',
                                           'nøyaktighet': 200,
                                           'synbarhet': '0'},
                              'oppdateringsdato': '2019-11-12T14:02:26',
                              'opphav': 'NIBIO',
                              'registreringsversjon': {'produkt': 'FKB-AR5',
                                                       'versjon': '4.5 '
                                                                  '20140301'},
                              'verifiseringsdato': '1987-07-01'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [[65.08172065833422,
                                             11.9483114567698],
                                            [65.08164987464349,
                                             11.948125827750276],
                                            [65.08162399742214,
                                             11.948045974566632],
                                            [65.08160498882513,
                                             11.947977043846667],
                                            [65.08158401298869,
                                             11.94793495160379]],
                            'type': 'LineString'},
               'properties': {'avgrensingType': '4206',
                              'datafangstdato': '1965-07-17',
                              'featuretype': 'ArealressursGrense',
                              'identifikasjon': {'lokalId': '000c12b4-3fca-4c42-bc24-0575c524342f',
                                                 'navnerom': 'AR5_test23',
                                                 'versjonId': '2019-11-11 '
                                                              '11:57:47.371000'},
                              'kvalitet': {'målemetode': '32',
                                           'nøyaktighet': 200,
                                           'synbarhet': '0'},
                              'oppdateringsdato': '2019-11-12T14:02:26',
                              'opphav': 'NIBIO',
                              'registreringsversjon': {'produkt': 'FKB-AR5',
                                                       'versjon': '4.5 '
                                                                  '20140301'},
                              'verifiseringsdato': '1965-07-17'},
               'type': 'Feature'}],
 'type': 'FeatureCollection'}

```

**Comment by larsop** [comment]
This JSON is not validating because of 
'versjon': '4.5 '
                                                                  '20140301'}

and 

'versjonId': '2019-11-11 '
                                                              '11:57:47.371000'

**Comment by strk** [comment]
What should this function return ? Do we start easy and just return VOID for now ?

**Comment by larsop** [comment]
> What should this function return ? Do we start easy and just return VOID for now ?

I am not sure, but do it easy for now.

**Comment by strk** [comment]
I confirm the validation issue. Will use the JSON in the first comment.
What I see in that JSON is that attributes can sometime be complex, as in:
```
           "identifikasjon": {
                    "lokalId": "092688bb-c6ef-43c9-b6f7-41b2f065537c",
                    "navnerom": "AR5_test23",
                    "versjonId": "2019-11-11 11:57:47.371000"
                },
```

The above in particular contains the identifier, is my understanding.
Is there a specification of the JSON format ? We'll need it to extract the primary key of features in the JSON.

The functionn description expects to use "primary key" as a way to tell if a feature was changed, deleted or added. But at the moment we are _not_ taking a primary key column name. We could add that parameter, but will a single column always be ok for a primary key or are composite primary keys ever used ?

**Comment by larsop** [comment]
> I confirm the validation issue. Will use the JSON in the first comment.
> What I see in that JSON is that attributes can sometime be complex, as in:
> 
> ```
>            "identifikasjon": {
>                     "lokalId": "092688bb-c6ef-43c9-b6f7-41b2f065537c",
>                     "navnerom": "AR5_test23",
>                     "versjonId": "2019-11-11 11:57:47.371000"
>                 },
> ```
> 
> The above in particular contains the identifier, is my understanding.
> Is there a specification of the JSON format ? We'll need it to extract the primary key of features in the JSON.
> 
> The functionn description expects to use "primary key" as a way to tell if a feature was changed, deleted or added. But at the moment we are _not_ taking a primary key column name. We could add that parameter, but will a single column always be ok for a primary key or are composite primary keys ever used ?

The spec is found here http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Ar5/4.6/FKB-Ar546.xsd (In Norwegian :) )

We use the lokalid and single column for a start.

**Comment by strk** [comment]
> We use the lokalid and single column for a start.

So you want me to hard-code `lokalid` as the name of the columns in the areal and lineal layers containing their primary keys ?

**Comment by larsop** [comment]
> > We use the lokalid and single column for a start.
> 
> So you want me to hard-code `lokalid` as the name of the columns in the areal and lineal layers containing their primary keys ?

It seems like we end with the same problems in JSON as we I have in other parts of the code.
The problem today Is that I have handcodet some mappings but that difficult to change in an efficient way.

So it seems like we need a Json mapping file together with the payload and some mapping JSON code to handle this.

**Comment by strk** [comment]
From phone call I'm updating the ticket to mention we want this function to also receive configuration instructions for mapping name of feature properties in the JSON to name of database columns in the target tables

**Comment by strk** [comment]
@larsop from http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Ar5/4.6/FKB-Ar546.xsd the `IdentifikasjonType` complex property is defined, with its `lokalId` child. is it then OK to avoid taking a mapping for that one ? Actually I see also other fields being mentioned, could you please state again, in this ticket, WHEN mapping gets useful ?

**Comment by strk** [comment]
According to the initial specification, the function should:
> Find out which features have been deleted (based on primary key)

In order to do so, I guess we want to also take a bounding box, as we probably don't want to DELETE all features which are just NOT in the JSON (rather we might want to delete features NOT in the JSON but still matching the FILTER used to obtain the JSON ? bbox, maybe even query  ?)

**Comment by larsop** [comment]
> @larsop from http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Ar5/4.6/FKB-Ar546.xsd the `IdentifikasjonType` complex property is defined, with its `lokalId` child. is it then OK to avoid taking a mapping for that one ? Actually I see also other fields being mentioned, could you please state again, in this ticket, WHEN mapping gets useful ?

For instance in NGIS we get the mapping for the unique ID in complex type, but from the client we get the simple ID in a simple type, thats why we need different mapping files.

**Comment by larsop** [comment]
edge_table
```

topo_ar5_sysdata_webclient.edge_attributes
                                                        Table "topo_ar5_sysdata_webclient.edge_attributes"
             Column             |               Type               | Collation | Nullable |                                Default                                 
--------------------------------+----------------------------------+-----------+----------+------------------------------------------------------------------------
 qms_id_grense                  | character varying                |           |          | 
 objtype                        | character varying                |           |          | 
 aravgrtype                     | character varying                |           |          | 
 maalemetode                    | character varying                |           |          | 
 noyaktighet                    | integer                          |           |          | 
 synbarhet                      | character varying                |           |          | 
 verifiseringsdato              | date                             |           |          | 
 datafangstdato                 | date                             |           |          | 
 kartid                         | character varying                |           |          | 
 kjoringsident                  | date                             |           |          | 
 arkartstd                      | character varying                |           |          | 
 opphav                         | character varying                |           |          | 
 informasjon                    | character varying                |           |          | 
 registreringsversjon_produkt   | character varying                |           |          | 
 registreringsversjon_versjon   | character varying                |           |          | 
 registreringsversjon_undertype | character varying                |           |          | 
 qms_navnerom                   | character varying                |           |          | 
 qms_versjonid                  | character varying                |           |          | 
 qms_oppdateringsdato           | timestamp without time zone      |           |          | 
 qms_prosesshistorie            | character varying                |           |          | 
 qms_kopidata_omraadeid         | integer                          |           |          | 
 qms_kopidata_originaldatavert  | character varying                |           |          | 
 qms_kopidata_kopidato          | timestamp without time zone      |           |          | 
 sl_dummy_grense_id             | integer                          |           |          | 
 geo                            | topogeometry                     |           |          | 
 felles_egenskaper              | topo_rein.sosi_felles_egenskaper |           |          | 
 saksbehandler                  | character varying                |           |          | 
 id                             | integer                          |           | not null | nextval('topo_ar5_sysdata_webclient.edge_attributes_id_seq'::regclass)
 reinbeitebruker_id             | character varying                |           |          | 
 status                         | integer                          |           |          | 
Indexes:
    "edge_attributes_id_idx" btree (((geo).id))
    "edge_attributes_id_idx1" UNIQUE, btree (id)
    "edge_attributes_id_idx2" btree (((geo).id))
Check constraints:
    "check_topogeom_geo" CHECK ((geo).topology_id = 207 AND (geo).layer_id = 1 AND (geo).type = 2)

face_table

```
```
\d topo_ar5_sysdata_webclient.face_attributes
                                                        Table "topo_ar5_sysdata_webclient.face_attributes"
             Column             |               Type               | Collation | Nullable |                                Default                                 
--------------------------------+----------------------------------+-----------+----------+------------------------------------------------------------------------
 qms_id_flate                   | character varying                |           |          | 
 objtype                        | character varying                |           |          | 
 arealtype                      | character varying                |           |          | 
 skogbonitet                    | character varying                |           |          | 
 treslag                        | character varying                |           |          | 
 grunnforhold                   | character varying                |           |          | 
 areal                          | numeric                          |           |          | 
 maalemetode                    | character varying                |           |          | 
 noyaktighet                    | integer                          |           |          | 
 synbarhet                      | character varying                |           |          | 
 verifiseringsdato              | date                             |           |          | 
 datafangstdato                 | date                             |           |          | 
 kartid                         | character varying                |           |          | 
 kjoringsident                  | date                             |           |          | 
 arkartstd                      | character varying                |           |          | 
 opphav                         | character varying                |           |          | 
 informasjon                    | character varying                |           |          | 
 registreringsversjon_produkt   | character varying                |           |          | 
 registreringsversjon_versjon   | character varying                |           |          | 
 registreringsversjon_undertype | character varying                |           |          | 
 qms_navnerom                   | character varying                |           |          | 
 qms_versjonid                  | character varying                |           |          | 
 qms_oppdateringsdato           | timestamp without time zone      |           |          | 
 qms_prosesshistorie            | character varying                |           |          | 
 qms_kopidata_omraadeid         | integer                          |           |          | 
 qms_kopidata_originaldatavert  | character varying                |           |          | 
 qms_kopidata_kopidato          | timestamp without time zone      |           |          | 
 sl_dummy_flate_id              | integer                          |           |          | 
 geo                            | topogeometry                     |           |          | 
 felles_egenskaper              | topo_rein.sosi_felles_egenskaper |           |          | 
 saksbehandler                  | character varying                |           |          | 
 id                             | integer                          |           | not null | nextval('topo_ar5_sysdata_webclient.face_attributes_id_seq'::regclass)
 reinbeitebruker_id             | character varying                |           |          | 
 status                         | integer                          |           |          | 
 editing_rights                 | text[]                           |           |          | 
Indexes:
    "face_attributes_id_idx" btree (((geo).id))
    "face_attributes_id_idx1" UNIQUE, btree (id)
Check constraints:
    "check_topogeom_geo" CHECK ((geo).topology_id = 207 AND (geo).layer_id = 2 AND (geo).type = 3)


```

**Comment by strk** [comment]
Other thing we need to map is the "feature type", beacause a "featureset" (as returned by NGIS) can contain 2 (or maybe in the future more?) types of features, which go to _different_ tables, is my understaning. I still think ad-hoc functions would be easier to manage in the long run. We'd then have 4 different functions:

   - Take FKB-Ar546 JSON payload and apply to database
   - Produce FKB-Ar546 JSON payload from database
   - Take Webclient JSON payload and apply to database
   - Produce Webclient JSON payload from database

**Comment by larsop** [comment]
> Other thing we need to map is the "feature type", beacause a "featureset" (as returned by NGIS) can contain 2 (or maybe in the future more?) types of features, which go to _different_ tables, is my understaning. I still think ad-hoc functions would be easier to manage in the long run. We'd then have 4 different functions:
> 

A nice thing with mapping files and tomcat/and so on is that you change them in git and and just deploy and files are sent to the correct server. With SQL function we do not handle it that well but that probably  we miss good routines.

>     * Take FKB-Ar546 JSON payload and apply to database
> 
>     * Produce FKB-Ar546 JSON payload from database
> 

Correct both of those are needed.

>     * Take Webclient JSON payload and apply to database
> 

We handles this but code to complex and should replaced by your new code.

>     * Produce Webclient JSON payload from database

The JSON payload to client simple so that is handles by a simple view today and ST_AsTopojson

**Comment by strk** [comment]
One problem I see with mapping, for example, is this need to filter out which feature types go to which tables.
How about NOT sending different type of features to this function, but always just a SINGLE feature type for a SINGLE target table ? Would simplify things. We would pass a filter to NGIS to request ONLY areal features first, and then ONLY lineal features. Do you see drawbacks with this ?

**Comment by strk** [comment]
or we can map based on actual feature type (`'feature' -> 'type'` in json terms)

**Comment by larsop** [comment]
> or we can map based on actual feature type (`'feature' -> 'type'` in json terms)

"featuretype":"ArealressursGrense" = topo_ar5_sysdata_webclient.edge_attributes
"featuretype":"ArealressursFlate" = topo_ar5_sysdata_webclient.face_attributes

**Comment by larsop** [comment]
Here is file with 3 ar5 rows
[ar5_feature_collection_3_rows.json.gz](https://github.com/NibioOpenSource/pgtopo_update_sql/files/5824106/ar5_feature_collection_3_rows.json.gz)

**Comment by strk** [comment]
Ok I'm working on the mapping JSON specification, so it's useful to know exactly in how many ways we want to map.

I've implemented single-json-value to simple-postgresql-value, next I could do the composite postgresql types, but my test target table don't have any.

I'd use the actual final tables, like `topo_ar5.webclient_flate` and `topo_ar5.webclient_grense` but those ones are missing an UUID column. Should the UUID column be added there ? Or are those NOT the tables intended to contain data from NGIS ?

My understanding was the actual database objects to be used as targets would be:

  - topo_ar5_sysdata_webclient as the topology
  - topo_ar5.webclient_flate as the AREAL layer
  - topo_ar5.webclient_grense as the LINEAL layer

**Comment by larsop** [comment]
> Ok I'm working on the mapping JSON specification, so it's useful to know exactly in how many ways we want to map.
> 
> I've implemented single-json-value to simple-postgresql-value, next I could do the composite postgresql types, but my test target table don't have any.
> 

For A5 we used simple types to make thing simpler on database side since we started out mapping from an internal table structure like this 

```
\d grl_sk_ar5_v05_master.ar5_grense
                                Table "grl_sk_ar5_v05_master.ar5_grense"
             Column             |            Type             | Collation | Nullable |      Default      
--------------------------------+-----------------------------+-----------+----------+-------------------
 qms_id_grense                  | character varying(255)      |           |          | 
 objtype                        | character varying(40)       |           |          | 
 aravgrtype                     | character varying(4)        |           |          | 
 maalemetode                    | character varying(4)        |           |          | 
 noyaktighet                    | integer                     |           |          | 
 synbarhet                      | character varying(4)        |           |          | 
 verifiseringsdato              | date                        |           |          | 
 datafangstdato                 | date                        |           |          | 
 kartid                         | character varying(13)       |           |          | 
 kjoringsident                  | date                        |           | not null | 'now'::text::date
 arkartstd                      | character varying(8)        |           |          | 
 opphav                         | character varying(57)       |           |          | 
 informasjon                    | character varying(255)      |           |          | 
 registreringsversjon_produkt   | character varying(58)       |           |          | 
 registreringsversjon_versjon   | character varying(250)      |           |          | 
 registreringsversjon_undertype | character varying(60)       |           |          | 
 qms_navnerom                   | character varying(255)      |           |          | 
 qms_versjonid                  | character varying(61)       |           |          | 
 qms_oppdateringsdato           | timestamp without time zone |           |          | 
 qms_prosesshistorie            | character varying(250)      |           |          | 
 qms_kopidata_omraadeid         | integer                     |           |          | 
 qms_kopidata_originaldatavert  | character varying(63)       |           |          | 
 qms_kopidata_kopidato          | timestamp without time zone |           |          | 
 geo                            | geometry(LineString,4258)   |           |          | 
 sl_dummy_grense_id             | integer                     |           |          | 
Indexes:
    "ar5_grense_geo_idx" gist (geo)
    "ar5_grense_qms_id_grense_idx" btree (qms_id_grense)
    "ar5_grense_qms_id_grense_idx1" UNIQUE, btree (qms_id_grense)

\d grl_sk_ar5_v05_master.ar5_flate
                                 Table "grl_sk_ar5_v05_master.ar5_flate"
             Column             |            Type             | Collation | Nullable |      Default      
--------------------------------+-----------------------------+-----------+----------+-------------------
 qms_id_flate                   | character varying(255)      |           |          | 
 objtype                        | character varying(40)       |           |          | 
 artype                         | character varying(4)        |           |          | 
 arskogbon                      | character varying(4)        |           |          | 
 artreslag                      | character varying(4)        |           |          | 
 argrunnf                       | character varying(4)        |           |          | 
 areal                          | numeric(18,5)               |           |          | 
 maalemetode                    | character varying(4)        |           |          | 
 noyaktighet                    | integer                     |           |          | 
 synbarhet                      | character varying(4)        |           |          | 
 verifiseringsdato              | date                        |           |          | 
 datafangstdato                 | date                        |           |          | 
 kartid                         | character varying(13)       |           |          | 
 kjoringsident                  | date                        |           | not null | 'now'::text::date
 arkartstd                      | character varying(8)        |           |          | 
 opphav                         | character varying(50)       |           |          | 
 informasjon                    | character varying(500)      |           |          | 
 registreringsversjon_produkt   | character varying(51)       |           |          | 
 registreringsversjon_versjon   | character varying(50)       |           |          | 
 registreringsversjon_undertype | character varying(53)       |           |          | 
 qms_navnerom                   | character varying(255)      |           |          | 
 qms_versjonid                  | character varying(54)       |           |          | 
 qms_oppdateringsdato           | timestamp without time zone |           |          | 
 qms_prosesshistorie            | character varying(256)      |           |          | 
 qms_kopidata_omraadeid         | integer                     |           |          | 
 qms_kopidata_originaldatavert  | character varying(56)       |           |          | 
 qms_kopidata_kopidato          | timestamp without time zone |           |          | 
 geo                            | geometry(Polygon,4258)      |           |          | 
 representasjonspunkt           | geometry(Point,4258)        |           |          | 
 sl_dummy_flate_id              | integer                     |           |          | 
Indexes:
    "ar5_flate_artype_idx" btree (artype)
    "ar5_flate_geo_idx" gist (geo)
    "ar5_flate_qms_id_flate_idx" btree (qms_id_flate)
    "ar5_flate_qms_id_flate_idx1" UNIQUE, btree (qms_id_flate)

```

When get simple mapping to composite types we can mayby use types like we did for reindrift something like this.

```

-- A composite type to hold sosi kopi_data
CREATE TYPE topo_rein.sosi_kopidata 
AS (
	omradeid smallint,
	originaldatavert  VARCHAR(50),
	kopidato DATE
);

-- A composite type to hold sosi registreringsversjon
CREATE TYPE topo_rein.sosi_registreringsversjon 
AS (
	produkt varchar,
	versjon varchar
);


-- A composite type to hold sosi kvalitet
-- beskrivelse av kvaliteten på stedfestingen
CREATE TYPE topo_rein.sosi_kvalitet 
AS (
	-- metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss
	-- TODO Hentes fra kode tabell eller bruke en constraint ???
	maalemetode smallint,
	
	-- punktstandardavviket i grunnriss for punkter samt tverravvik for linjer
	-- Merknad: Oppgitt i cm
	noyaktighet integer,

	-- hvor godt den kartlagte detalj var synbar ved kartleggingen
	-- TODO Hentes fra kode tabell eller bruke en constraint ???
	synbarhet smallint
);

-- A composite type to hold sosi sosi felles egenskaper
CREATE TYPE topo_rein.sosi_felles_egenskaper
AS (
	-- identifikasjondato når data ble registrert/observert/målt første gang, som utgangspunkt for første digitalisering
	-- Merknad:førsteDatafangstdato brukes hvis det er av interesse å forvalte informasjon om når en ble klar over objektet. Dette kan for eksempel gjelde datoen for første flybilde som var utgangspunkt for registrering i en database.
	-- lage regler for hvordan den skal brukes, kan i mange tilfeller arves
	-- henger sammen med UUID, ny UUID ny datofangst dato
	forstedatafangstdato DATE,

	-- Unik identifikasjon av et objekt, ivaretatt av den ansvarlige produsent/forvalter, som kan benyttes av eksterne applikasjoner som referanse til objektet. 
	-- NOTE1 Denne eksterne objektidentifikasjonen må ikke forveksles med en tematisk objektidentifikasjon, slik som f.eks bygningsnummer. 
	-- NOTE 2 Denne unike identifikatoren vil ikke endres i løpet av objektets levetid. 
	-- TODO Test if we can use this as a unique id.
	identifikasjon varchar,
	-- bygd opp navnerom/lokalid/versjon
	-- navnerom: NO_LDIR_REINDRIFT_VAARBEITE
	-- versjon: 0
	-- lokalid:  rowid	
	-- eks identifikasjon = "NO_LDIR_REINDRIFT_VAARBEITE 0 199999999"


	-- beskrivelse av kvaliteten på stedfestingen
	-- Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.
	kvalitet topo_rein.sosi_kvalitet,

	
	-- dato for siste endring på objektetdataene 
	-- Merknad: Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).
	-- Definition: Date and time at which this version of the spatial object was inserted or changed in the spatial data set. 
	oppdateringsdato DATE, 

	-- referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde
	-- Merknad: Kan også beskrive navn på person og årsak til oppdatering
	opphav VARCHAR(255),

	-- dato når dataene er fastslått å være i samsvar med virkeligheten 
	-- Merknad: Verifiseringsdato er identisk med ..DATO i tidligere versjoner av SOSI	verifiseringsdato DATE
	-- lage regler for hvordan den skal brukes
	-- flybilde fra 2008 vil gi data 2008, må være input fra brukeren
	verifiseringsdato DATE,

	-- Hva gjør vi med disse verdiene som vi har brukt tidligere brukte  i AR5 ?
	-- Er vi sikre på at vi ikke trenger de

	-- datafangstdato DATE, 
	-- Vet ikke om vi skal ha med den, må tenke litt
	-- Skal ikke være med hvis Knut og Ingvild ikke sier noe annet
	
	-- vil bli et produktspek til ???
	-- taes med ikke til slutt brukere
	informasjon  VARCHAR(255) ARRAY, 
	
	-- trengs ikke i følge Knut og Ingvild
	-- kopidata topo_rein.sosi_kopidata, 
	
	-- trengs ikke i følge Knut og Ingvild
	-- prosess_historie VARCHAR(255) ARRAY,
	
	-- kan være forskjellige verdier ut fra når data ble lagt f.eks null verdier for nye attributter eldre enn 4.0
	-- bør være med
	registreringsversjon topo_rein.sosi_registreringsversjon

	
);


-- this is type used extrac data from json
CREATE TYPE topo_rein.simple_sosi_felles_egenskaper AS (
	"fellesegenskaper.forstedatafangstdato" date , 
	"fellesegenskaper.verifiseringsdato" date ,
	"fellesegenskaper.oppdateringsdato" date ,
	"fellesegenskaper.opphav" varchar, 
	"fellesegenskaper.kvalitet.maalemetode" int ,
	"fellesegenskaper.kvalitet.noyaktighet" int ,
	"fellesegenskaper.kvalitet.synbarhet" smallint
	
);

```



> I'd use the actual final tables, like `topo_ar5.webclient_flate` and `topo_ar5.webclient_grense` but those ones are missing an UUID column. Should the UUID column be added there ? Or are those NOT the tables intended to contain data from NGIS ?
>

Yes thouse needs be added.
 
> My understanding was the actual database objects to be used as targets would be:
> 
>     * topo_ar5_sysdata_webclient as the topology
> 
>     * topo_ar5.webclient_flate as the AREAL layer
> 
>     * topo_ar5.webclient_grense as the LINEAL layer

Yes that correct .

**Comment by strk** [comment]
I filed #24 to add the missing UUID columns

**Comment by strk** [comment]
In phone call we decided to deal with mapping function separately from this function, so this work will need to wait for #25 to be completed.
