### ISSUE TITLE
topo_update test fails

### ISSUE THREAD

**Issue by strk** [NibioOpenSource/pgtopo_update_sql#20]
Here's the diff between expected and obtained output from the test:
```
--- topo_update_expected        2021-01-13 17:00:39.241917098 +0100
+++ /tmp/pgis_reg/test_1_out    2021-01-14 17:30:36.576327288 +0100
@@ -197,7 +197,7 @@
 59_layer_accept_update|2
 59_sommer_data_update_log_c3|0
 59_sommer_r3|11|ZH|4|(4,2,11,3)|1|ole|2013-08-26|2015-07-26|2016-07-26
-59_sommer_r3|10|ZH|4|(4,2,10,3)|1|ole|2013-08-26|2015-07-26|2016-07-26
+59_sommer_r3|10|ZH|4|(4,2,8,3)|1|ole|2013-08-26|2015-07-26|2016-07-26
 59_sommer_split|1
 59_sommer_split_b|1
 59_sommer_r4|15|ZH|4|(4,2,15,3)|1|ole|2013-08-26|2015-07-26
```

I don't know what are those numbers `(4,2,8,3)` vs `(4,2,10,3)` but they do sound like TopoGeometry objects ?
In that case: should the test print some other information about the geometries rather than their identifiers ?

**Comment by larsop** [comment]
It was topogeom may be related upgrading latest postgis and postgres , remove object from (54ec1c3..d3cf82c)
PostgreSQL 13.1 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit
POSTGIS="3.1.0 5e2af69" [EXTENSION] PGSQL="130" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY
(
