### ISSUE TITLE
Documentation for  return code of create_surface_edge_domain_obj is wrong.

### ISSUE THREAD

**Issue by strk** [NibioOpenSource/pgtopo_update_sql#38]
The function is documented (in comments) to return a list of identifiers for the newly created TopoGeometry surfaces but the actual return type is a `TABLE(result text)` and the actual value is a JSON, this is all a bit confusing. 

From reading the code the return is a set of rows represented as a JSON object. The returned ROWS are possibly of different types, if I read the code correctly: some rows are for new border features and some rows are for new surface features, is this correct ?

If the goal is to get a list of objects created (in either the Borders or the Surfaces layers), could it be more appropriate to return just identifiers of those new objects, in case caller doesn't care about all attributes ?
Or do we want to NOT require the use of primary keys in Surface and Border layers ?

**Comment by larsop** [comment]
We got error in Java some years ago related when using JSON so we just used text to get around in a easy way.

We get back "[{"id":1,"id_type":"S"}] and use that to identify the id's that should be sent to the clients for setting attribute values.

**Comment by strk** [comment]
Ok, so the code makes an assumption about the target topology layers having a unique constraint on the TopoGeometry identifier (this is not done by PostGIS Topology itself). And also assume that access-via-TopoGeometry id is fast. Should be documented accordingly.

Regarding return type: any reason not to return 2 arrays ? Or, if we expect the function to always create a SINGLE border, a single identifier for the border TopoGeometry and an array for the surface TopoGeometries ?

**Comment by strk** [comment]
Also: any reason to return a TABLE rather than just a single TEXT value ? The function is returning a single json object anway

**Comment by larsop** [comment]
The idea at the start was to pas this as JSON to client, but now this read by the java also.
