### ISSUE TITLE
make check: ERROR:  role "topo_update" does not exist

### ISSUE THREAD

**Issue by strk** [NibioOpenSource/pgtopo_update_sql#4]
The error is spotted by travis: https://travis-ci.org/NibioOpenSource/pgtopo_update_sql#L187

Happens as topo_update-post.sql uses "DROP OWNER BY topo_update" but there's no code creating that role. Maybe it should be "DROP OWNED BY topo_rein_update_role" which is created by topo_update-pre.sql.

I'd also advice to use roles with name explicitly bound to testing

**Comment by larsop** [comment]
Fixed and checked into develop

**Comment by strk** [comment]
Confirmed, as of bf6314b54bd5e7174241146a67671f7e3da7e414
