### ISSUE TITLE
Generic TopoJson producer

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#6]
Be able to produce TopoJson for any TopoLayer (point, line  and surface).
Possible to restrict the rows based on bounding box 
Possible to restrict layers based on some where condition like a list of id's. 
Project to given srid
crs information with epsg code should be added to the TopoJson output. 
Also support offset values
By default it should pick all attributes on given layer, but maybe it should be possible to restrict columns.
May ad a max feature value

**Comment by strk** [comment]
I've seen a function taking regclass was added, should that one be built upon ?

**Comment by strk** [comment]
Other question: each TopoJSON feature must have an identifier. Is it ok to use the TopoGeometry identifier rather than "guessing" which field identifies the row ?

The TopoGeometry identifier is most probably unique within its own topology and topolayer, it is extracted with `id(topocolumn)`.

**Comment by strk** [comment]
I'm thinking the function could take an arbitrary query as input.
Doing so, all restrictions would be specified in the query (bounding box, list of ids, max features, offset, output attributes).

**Comment by strk** [comment]
@larsop See how you like e641c53906d902db6caa9279d90dbc72597c3486
`SELECT query_to_topojson(query, out_srid, numdigits)`

**Comment by larsop** [comment]
Thanks that seems to work very nice. I did a test both for line and surface and that worked well.

Is it possible to add add the srid info to the topojson in the way same as geojson ?
"crs":{"type":"name","properties":{"name":"EPSG:32632"}}},

**Comment by strk** [comment]
Uhm, I find no trace of that in the TopoJSON documentation.
Is it ok to put the "crs" element directly under the top-level
Topology object ? Like:

``` json
 {
    "type": "Topology",
    "crs": { ... },
    "objects": { ... }
 }
```

**Comment by larsop** [comment]
Yes do to that for now and I will check with that guy that works on the GUI side when he is back next week.

Do you know why this is not defined in TopoJSON ?

**Comment by strk** [comment]
I guess that's because "CRS" is inherently related to a geometry object.
Anyway from the GeoJSON spec I've read it's ok to put "crs" in any geometry object's parent, so I guess it's also ok to put it under topology...

**Comment by strk** [comment]
REF: http://geojson.org/geojson-spec.html#coordinate-reference-system-objects

**Comment by larsop** [comment]
It seems like we also should avoid to use EPSG and use "urn:.....", but for now we use EPSG.

**Comment by strk** [comment]
See e5c77cf, please open a new ticket for new requests or bugs

**Comment by larsop** [comment]
Thanks, tested and the crs is in

SELECT  topo_rein.query_to_topojson('select \* from topo_rein.arstidsbeite_var_grense', 32632, 0);

query_to_topojson | {"type":"Topology", "crs":{"type":"name","properties":{"name":"EPSG:32632"}},"objects":{"1":{ "type": "MultiLineString", "arcs": [[0]],"properties":{"id":1,"felles_egenskaper":{"forstedatafangstdato":"2015-10-06","identifikasjon":"NO_LDIR_REINDRIFT_VAARBEITE 0 0","kvalitet":{"maalemetode":99,"noyaktighet":200,"synbarhet":0},"oppdateringsdato":null,"opphav":"komnr","verifiseringsdato":"2015-10-06","informasjon":null,"registreringsversjon":{"produkt":null,"versjon":"4.5"}}}}},"arcs": [[[308101,6494806],[308209,6494804],[308243,6495071],[308097,6495076],[308101,6494806]]]}
