### ISSUE TITLE
topo_rein.query_to_topojson error when no other attributes than topo

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#7]
If I have this table 

 \d topo_rein.new_surface_data_for_edge;
Table "topo_rein.new_surface_data_for_edge"
    Column    |     Type     | Modifiers 
--------------+--------------+----------- 
 surface_topo | topogeometry | 

with this content

[local] lop@sl=# select surface_topo from topo_rein.new_surface_data_for_edge;
##  surface_topo 

 (461,2,5,3)
 (461,2,6,3)

And if I run query_to_topojson

[local] lop@sl=# SELECT  topo_rein.query_to_topojson('select surface_topo from topo_rein.new_surface_data_for_edge', 4258,5);
NOTICE:  00000: Field: surface_topo of type topogeometry
LOCATION:  exec_stmt_raise, pl_exec.c:3068
ERROR:  22004: query string argument of EXECUTE is null
CONTEXT:  PL/pgSQL function topo_rein.query_to_topojson(text,integer,integer) line 78 at FOR over EXECUTE statement
LOCATION:  exec_dynquery_with_params, pl_exec.c:6474

**Comment by strk** [comment]
can you show the result of `SELECT * FROM topology.topology WHERE id = 461` ?

**Comment by strk** [comment]
oh, never mind I think I know what this is about: lack of attributes. Can you confirm that adding an attribute, like changing the query to be: `SELECT topo_rein.query_to_topojson('select surface_topo,0 from topo_rein.new_surface_data_for_edge', 4258,5);` fixes the error ?

**Comment by strk** [comment]
how do you want the topojson to look in those cases ?
Should the "properties" element be completely omitted or should it be set to an empty object ?

**Comment by strk** [comment]
Empty properties pushed. Feel free to reopen if you want a different solution.

**Comment by larsop** [comment]
Thanks tested and  it works.

query_to_topojson | {"type":"Topology", "crs":{"type":"name","properties":{"name":"EPSG:4258"}},"objects":{"5":{ "type": "MultiPolygon", "arcs": [[[-5,-4,-3,-2,-1]]],"properties":{}},"6":{ "type": "MultiPolygon", "arcs": [[[1,2,3,-8,-7,-6]]],"properties":{}}},"arcs": [[[5.70152,58.55373],[5.70178,58.55167]],[[5.70178,58.55167],[5.70276,58.55252],[5.704,58.55354]],[[5.704,58.55354],[5.70431,58.5538]],[[5.70431,58.5538],[5.70457,58.554]],[[5.70457,58.554],[5.7049,58.55497],[5.70152,58.55373]],[[5.70178,58.55167],[5.70182,58.55131]],[[5.70182,58.55131],[5.70368,58.55134]],[[5.70368,58.55134],[5.70457,58.554]]]}
