### ISSUE TITLE
ERROR: TopoJSON export does not support puntual objects

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#9]
What the best way to get around this problem ?

I was hoping to use the same structure input parameters as for query_to_topojson:

**Comment by strk** [comment]
According to the specs Point and Multipoint are valid members of a topology:
https://github.com/mbostock/topojson-specification/blob/master/README.md#22-geometry-objects

I'll look at a local workaround but best would be implementing the puntual type support upstream:
https://trac.osgeo.org/postgis/ticket/3343

**Comment by larsop** [comment]
Thats very nice. 

Do you know when a workaround maybe ready ?

Here is a example on how I produce a simple case that fails

SELECT topo_update.create_point_point_domain_obj('{"type": "Feature","crs":{"type":"name","properties":{"name":"EPSG:4258"}},"geometry":{"type":"Point","coordinates":[17.4122416312598,68.6013397740665]},"properties":{"reinbeitebruker_id":"XG","reindriftsanleggstype":18}}');

SELECT  topo_rein.query_to_topojson('select \* from topo_rein.reindrift_anlegg_punkt', 32632, 0);

Returns

ERROR:  P0001: TopoJSON export does not support puntual objects
CONTEXT:  PL/pgSQL function topo_rein.query_to_topojson(text,integer,integer) line 90 at FOR over EXECUTE statement
LOCATION:  exec_stmt_raise, pl_exec.c:3068

**Comment by strk** [comment]
Ready :)

**Comment by larsop** [comment]
Thanks, tested and it works.
